//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeemAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintainanceHistory
    {
        public int userTransportationId { get; set; }
        public int shopId { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<double> cost { get; set; }
        public string description { get; set; }
    
        public virtual CustomerTransportation CustomerTransportation { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
