//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeemAPI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XeemEntities : DbContext
    {
        public XeemEntities()
            : base("name=XeemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerTransportation> CustomerTransportations { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<QuotePrice> QuotePrices { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopQuote> ShopQuotes { get; set; }
        public virtual DbSet<SystemPrice> SystemPrices { get; set; }
        public virtual DbSet<Transportation> Transportations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MaintainanceHistory> MaintainanceHistories { get; set; }
        public virtual DbSet<TransportationPhoto> TransportationPhotos { get; set; }
    }
}
